# Generated by Django 4.2.4 on 2023-10-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterModel',
            fields=[
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=254)),
                ('mobile_num', models.TextField(default='+880')),
                ('study_level', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('age', models.ImageField(upload_to='')),
                ('address', models.TextField(default='Address')),
            ],
        ),
    ]
