# Generated by Django 4.2.4 on 2023-10-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodel',
            name='password1',
            field=models.TextField(default='123', max_length=100),
        ),
        migrations.AddField(
            model_name='registermodel',
            name='password2',
            field=models.TextField(default='123', max_length=100),
        ),
        migrations.AddField(
            model_name='registermodel',
            name='username',
            field=models.CharField(default='abcd', max_length=100),
        ),
    ]
