# Generated by Django 4.2.4 on 2023-10-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_registermodel_password1_registermodel_password2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='age',
            field=models.IntegerField(),
        ),
    ]
