# Generated by Django 4.2.4 on 2023-11-04 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_registermodel_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicPythonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam1', models.IntegerField()),
                ('exam2', models.IntegerField()),
                ('exam3', models.IntegerField()),
                ('exam4', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OOPPythonModel',
            fields=[
                ('basicpythonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.basicpythonmodel')),
                ('name', models.CharField(max_length=200)),
            ],
            bases=('courses.basicpythonmodel',),
        ),
        migrations.CreateModel(
            name='PythonCourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_users', to='users.registermodel')),
            ],
        ),
        migrations.AddField(
            model_name='basicpythonmodel',
            name='pyid1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pyid_1', to='courses.pythoncoursemodel'),
        ),
    ]
